# Build stage
FROM golang:1.23.4-alpine

# Set working directory
WORKDIR /app

# Install Air
RUN go install github.com/airverse/air@latest

# Copy go mod and sum files
COPY go.mod go.sum ./
RUN go mod download

# Copy the source code
COPY . .

# Expose the port
EXPOSE 8081

# Run Air
CMD ["air"]
