name: Build and Deploy

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        # Remove the container section to use the default Ubuntu runner
        # container:
        #   image: alpine:latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0 # This ensures git history is available for version info

            - name: Set repository name
              id: repo-name
              run: |
                  REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
                  REPO_NAME=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')
                  echo "REPO_OWNER=$REPO_OWNER" >> $GITHUB_ENV
                  echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
            - name: Create .env file
              run: |
                  cat > .env << EOL
                  ATLAS_ENVIRONMENT=${{ secrets.ATLAS_ENVIRONMENT }}
                  ATLAS_CLUSTER=${{ secrets.ATLAS_CLUSTER }}
                  ATLAS_USER=${{ secrets.ATLAS_USER }}
                  ATLAS_PASS=${{ secrets.ATLAS_PASS }}
                  EOL
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
              with:
                  install: true
                  driver-opts: |
                      image=moby/buildkit:buildx-stable-1

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                  context: .
                  push: true
                  tags: |
                      ghcr.io/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}:latest
                      ghcr.io/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}:${{ github.sha }}
                  # Use GitHub Actions cache without BuildX-specific options
                  cache-from: type=registry,ref=ghcr.io/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}:buildcache
                  cache-to: type=registry,ref=ghcr.io/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}:buildcache,mode=max

            - name: Deploy to Digital Ocean
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.DO_HOST }}
                  username: ${{ secrets.DO_USERNAME }}
                  key: ${{ secrets.DO_SSH_KEY }}
                  script: |
                      # Login to GitHub Container Registry
                      echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

                      # Pull the latest image (using lowercase repository name)
                      docker pull ghcr.io/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}:latest

                      # Stop and remove the existing container (if it exists)
                      docker stop activity-service || true
                      docker rm activity-service || true

                      # Run the new container with port 8081
                      docker run -d --name activity-service --restart unless-stopped -p 8081:8081 ghcr.io/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}:latest

                      # Clean up unused images
                      docker image prune -f
